### ISSUE TITLE
Footer displayed but not header

### ISSUE THREAD

**Issue by studioavanti** [Nikschavan/bb-header-footer#10]
I already posted on wordpress.org, so just in case you miss it (sorry for the duplicate). 
Just a little issue for me: i use custom BB global saved rows as header and footer, select these items in BB Header Footer plugin’s options, footer is well displayed but header is not, i can’t figure why.
I use BB 1.8.7.1 plugin Pro version and BB Theme.

**Comment by Nikschavan** [comment]
Can you still reproduce it when you select a different page as header or even a different template?

**Comment by studioavanti** [comment]
Hi Nikschavan,

Yes, i tried with a copy of my BB global saved row elements, saved in a WP page. 
I tried with a complete different page too: header still doesn't display.
Curious thing is that footer's allright with a BB global saved row (BB template). 

Some clues about my configuration if it helps: 
- Before discovering BB Header Footer plugin, i used global saved rows directly in my BB layouts instead of theme's header and footer. So header and footer were hidden in BB theme's WP customizer. 
- I use PRO version of BB (not free, not Agency), BB theme, Ultimate Addons for BB and BeaverAddons PowerPack + some other WP plugins.

**Comment by Nikschavan** [comment]
Afer disabling the plugin, is the default theme's header displayed? I am guessing the theme's settings for header layout could be set to `none`?

**Comment by studioavanti** [comment]
Actually, BBHF plugin enabled or disabled, no header is displayed unless i insert a BB template custom header directly in the layout. 
And yes, i disabled theme's header and footer in WP customizer: see attached (in french, sorry).
Does this match what you suppose?
![capture d ecran 2016-10-20 a 17 33 24](https://cloud.githubusercontent.com/assets/8690161/19566641/5b575ce0-96eb-11e6-92e2-bf81149baece.png)

**Comment by studioavanti** [comment]
OK, i think i get your point: i selected "NAV bellow" in WP customizer and my custom header is now displayed (see attached). 
Is it the thing to do? 
But footer doesn't need this WP customizer activation to display…
![capture d ecran 2016-10-20 a 17 35 39](https://cloud.githubusercontent.com/assets/8690161/19566846/fc2b9ec4-96eb-11e6-8923-e0a0fa59d913.png)

**Comment by Nikschavan** [comment]
Yeah, you must enable the header in the theme options.

After you disable this plugin, it should display the theme's header. This plugin basically just replaces the theme header.

And if tou have disabled the header in theme settings, header from the plugin will also be disabled.

**Comment by studioavanti** [comment]
Sure, it make sens. 
Thanks for your help ;-)

**Comment by Nikschavan** [comment]
I will go ahead and close this issue.
