### ISSUE TITLE
Hey, your current theme is not supported by BB Header Footer

### ISSUE THREAD

**Issue by hudpr** [Nikschavan/bb-header-footer#15]
Hello
I have a web page with installed:
- WordPress 4.7.1
- Beaver Builder Plugin 1.9
- Beaver Builder Theme 1.5.3

I get the information like:
"Hey, your current theme is not supported by BB Header Footer, click here to check out the supported themes."
Question is why?
Could You help me?
Best regards,

**Comment by Nikschavan** [comment]
Can you tell me what is the folder name of you theme?

Have you modified the bb theme somehow?

**Comment by hudpr** [comment]
Folder name: "bb-theme-1.5.3".
I didn.t modify theme.

**Comment by Nikschavan** [comment]
The name of the folder should only be `bb-theme` As the name of the folder is different WordPress has named the slug of the theme `bb-theme-1.5.3` and hence this plugin cannot detect this as the supported theme.

To fix - 

1. Activate some other theme.
2. Rename the directory of the theme to be just `bb-theme`
3. Activate the bb-theme again.

After this WordPress will get the correct slug of the theme and the problem should be fixed.

**Comment by hudpr** [comment]
It works!
Thank You very much.
