### ISSUE TITLE
Any theme support

### ISSUE THREAD

**Issue by webmandesign** [Nikschavan/bb-header-footer#24]
Hi,

Thanks for this great plugin!

I have a suggestion for an improvement. It would be nice to have a possibility to hook onto this plugin from any theme so the theme developers can add the plugin support into their themes.

Thanks for consideration!

Regards,

Oliver

**Comment by webmandesign** [comment]
Please see my pull request #25 for resolution of this issue.

Simply, if a theme declares support for Beaver Builder Header Footer plugin via `add_theme_support( 'bb-header-footer' );` the plugin should not display the incompatibility admin notices and let the theme do the compatibility job in its codebase.

**Comment by webmandesign** [comment]
Hi,

Do you have any ETA on this please? I'm releasing a theme update today which contains the compatibility already so I would like to promote it in theme documentation and description page. Or can you maybe tell me the version number of the plugin this functionality will be included in please?

Thanks!

**Comment by webmandesign** [comment]
BTW, you can close this issue I think.

**Comment by Nikschavan** [comment]
I will add this in the next update of the plugin. v1.1.3.

I am also working on similar [plugin for elementor](https://github.com/Nikschavan/elementor-header-footer) So I was hoping to have this theme support similar for both the plugins. But that will probably need a more than a week or so.

I will merge and close this for now and will ping you when I have made compatibility for both the plugins similar.

**Comment by webmandesign** [comment]
Thanks! Elementor is not that hot for me, so take your time ;)
