### ISSUE TITLE
Call the Beaver Builder shortcode function directly

### ISSUE THREAD

**Issue by webmandesign** [Nikschavan/bb-header-footer#28]
A small improvement suggestion: Instead of calling `do_shortcode( '[fl_builder_insert_layout id=...` please load the shortcode directly with `FLBuilderShortcodes::insert_layout( array( 'id' =>...`.

**Comment by Nikschavan** [comment]
Thank you for this @webmandesign,

BB 1.10 alpha has added a new method `FLBuilder::render_content_by_id` which just loads the markup and the assets can be separately enqueued in the `wp_enqueue_scripts` which would be a nice to have.
but as BB 1.10 is not yet released, I will merge this and create a separate issue to use that function in next version.

**Comment by webmandesign** [comment]
Cool, sure, whatever is better for you. Thanks!
