### ISSUE TITLE
Load the CSS and JS in `wp_enqueue_scripts`

### ISSUE THREAD

**Issue by Nikschavan** [Nikschavan/bb-header-footer#30]
Right now when a template is loaded as header or footer all its assets are enqueued in the `<body>` where the shortcode was rendered.

BB 1.10 alpha has added a new method `FLBuilder::render_content_by_id()` which just loads the markup and the assets can be separately enqueued in the `wp_enqueue_scripts`

**Comment by webmandesign** [comment]
Wou, really? I thought WordPress allows loading assets with [`wp_enqueue_scripts` directly in shortcode function](https://mikejolley.com/2013/12/02/sensible-script-enqueuing-shortcodes/). Probably this would be better to open a ticket with Beaver Builder then?

**Comment by Nikschavan** [comment]
Unfortunately, the shortcode for BB's templates is not a straightforward shortcode. BB actually renders the content of the page inside the shortcode and during that, it has to manually load the assets as well.

PR #58 Fixes this.
