### ISSUE TITLE
Can Primer theme be supported?

### ISSUE THREAD

**Issue by sujaypawar** [Nikschavan/bb-header-footer#31]
GoDaddy's primer theme should be one of the most used theme with BB. Can you support it to be used with this plugin? If possible and necessary, you can send them a PR with hook you need.

**Comment by Nikschavan** [comment]
Yep, as godaddy users get primer theme and beaver builder preinstalled it would be nice to have them supported.

I'll close this issue as this is already being tracked [here](https://github.com/Nikschavan/bb-header-footer/issues/16)
