### ISSUE TITLE
Sub-menu Hidden Behind Content

### ISSUE THREAD

**Issue by luislad** [Nikschavan/bb-header-footer#39]
Hi!

So i created a custom header with beaver builder with beaver builder menu module. I set it as the header for the site pages.

If I choose to stay static on top of the page the submenu links appear fine,but if I set it to be sticky and to shrink the submenu links appear behind the content above unless the header has enough height to cover it. But when I scroll down and it shrinks then the submenu links appear just fine. If I set the header transparent I have no issues.

I tried to add custom css setting the overflow visible, position relative, and increasing Z-Index and nothing worked.

Sorry for my english but is not my native language!

Thank you!

**Comment by Nikschavan** [comment]
Closing this as it is resolved [on WordPress support](https://wordpress.org/support/topic/sub-menu-hidden-behind-content/).

**Comment by Nikschavan** [comment]
Reopening this issue as this might be needed to be fixed from the plugin after some testing.

CSS that fixed the issue - 
```
.bhf-fixed-header {
    position: relative;
    z-index: 20;
}
```
