### ISSUE TITLE
CSS classes being stripped

### ISSUE THREAD

**Issue by daveman321** [Nikschavan/bb-header-footer#56]
The current page item class is being stripped so the menu item is not being highlighted when on the current page. Our site is at http://beachcitytennis.com and if you go from page to page you'll see that the menu item is not highlighted and if you inspect the code, it's missing the current-menu-item and current-page-item classes. 

I asked the developers of Beaver Builder directly and in their test it seems to point to a bug in this bb header footer plugin. 

If you go here https://cl.ly/3o2G331s2k3H you'll see they created a test page and test menu at the bottom and that one shows the proper current menu item highlighted. You'll notice that the top menu item isn't highlighted and that is the one using the bb header footer plugin settings.

Please help, we've been trying to fix this for 2 weeks now, thanks!

**Comment by sandeshjangam** [comment]
I will check it...

**Comment by Nikschavan** [comment]
I got this from one of the users on Support channel if this helps to debug - 

The issue only happens from Beaver Builder 1.10.8 and beyond

**Comment by Nikschavan** [comment]
Hello @daveman321 I just fixed this in a PR #58,

Can you try this version once and let me know if your issue is fixed after this? - Compiled zip file of the plugin - https://cl.ly/n45f
